name       : lapack
version    : 3.6
release    : 1
source     :
    - http://www.netlib.org/lapack/lapack-3.6.0.tgz : a9a0082c918fe14e377bbd570057616768dca76cbdc713457d8199aaa233ffc3
license    : BSD-3-Clause
summary    : Basic Linear Algebra Subprograms
description: |
    Basic Linear Algebra Subprograms
builddeps  :
    - gfortran
setup      : |
    sed -e 's|/CMAKE/|/cmake/|' -i CBLAS/CMakeLists.txt
    mkdir build && cd build
    %cmake .. \
        -DBUILD_TESTING=OFF \
        -DCMAKE_Fortran_COMPILER=gfortran \
        -DLAPACKE=ON \
        -DCBLAS=ON \
        -DBUILD_DEPRECATED=ON \
        -DBUILD_SHARED_LIBS=ON
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
